name: rentify_inspection
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  photo_view: ^0.13.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/bgnd_textures/login_texture.png
    - assets/images/bgnd_textures/dashboard_texture.png
    - assets/images/bgnd_textures/secondary_texture.png
    - assets/images/JavaBook.png
    - assets/images/face.jpeg
    - assets/images/cnic_front.jpg
    - assets/images/cnic_back.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

